const questions = [
	'What are you doing?',
	'What is your name?',
	'Where do you live?',
	'Who is your celebrity crush?',
	"What's your biggest turn-off?",
	'What was your first impression of me?',
	'Do you like huge parties or would you rather spend time in a small group/alone?',
	"What's something weird that you find attractive?",
	"What's the best gift you've ever received and who was it from?",
	"What's one rule to live by?",
	"What's your biggest fear?",
	'Who are you closest to in your family?',
	"What's your love language?",
	'What do you do to relax?',
	"What's a typical Saturday look like for you?",
	'When it comes to priorities like work, life, family, and friends, how does each rank compared to the others?',
	'Are you a dog or cat person?',
	"What is one thing you wish you never did?",
	"Would you rather be incredibly intelligent or incredibly happy?",
	"What’s something you believe that most people don’t?",
	"If you could have one superpower for a day, what would it be?",
	"When in life have you been most nervous?",
	"What celebrity do you have the biggest crush on?",
	"What city has been the best city you’ve ever lived in or travelled to?",
	"What are you doing when you’re at your happiest?",
	"What’s something about your past that most people don’t know about?",
	"Where is the one place in the world that you want to travel to and why?",
	"What is your most bizarre habit?",
	"What was your favourite movie ever?",
	"What was the last book you read?",
	"What’s the best piece of advice that you received from your parents?",
	"What TV show could you just binge watch all day?",
	"What age has been your best so far?",
	"If you could go back in time and talk to yourself, what advice would you give?",
	"What’s the biggest regret you have?",
	"Would you rather be in love or have a lot of money?",
	"Are you a mountain or beach person?",
 "If you knew you would die in one month, what would you do?",
 "What’s your favorite type of music and why?",
 "If you could be incredibly skilled at one thing, what would you choose?",
 "If you won the lottery, what would be the first thing you would do?",
 "Would you rather be rich and famous or rich without the fame?",
 "If you could contact the whole world and they would listen, what message would you give?",
 "If you were an incredibly talented rapper, what would you want to rap about?",
 "What’s something you did in your past that your friends still tease you about?",
 "Do you prefer big parties or small gatherings?",
 "What was the worst age you’ve been so far?",
 "What’s your most common deal-breaker?",
 "If you could be a fictional superhero, who would you be?",
 "Do you believe in fate? Or are we in control of our lives?",
 "Do you believe in Karma?",
 "What’s something you find attractive that most people don’t?",
 "When you read the newspaper, what section to immediately skip to?",
 "Do you have any superstitions?",
 "What was the most frightening experience you’ve ever had?",
 "What non-politician do you wish would run for office?",
 "What’s a cheesy song that you love?",
 "If you could have a dinner date with anyone in the world, who would you choose?",
 "Do you stay up to date with current affairs?",
 "What is the best gift you’ve ever given someone?",
 "What’s the best gift you’ve ever received?",
 "Are you an apple or android person?",
 "If you could be the opposite sex for one day, what would you do?",
 "If you had to get your Mom one present and you could spend an unlimited amount, what would you get?",
 "What is the kindest thing someone has ever said about you?",
 "Would you prefer a huge mansion in a poor area or a small cosy apartment in a rich area?",
 "What is the weirdest thing about your family ?",
 "What do you do to calm yourself when you are angry?",
 "Do you ever consciously try to look good in front of other people?",
 "What is one rule that defines your life?",
 "If you have a free day, how do you usually spend it?",
 "What is the one thing you spend money on when you know you shouldn’t",
 "What is one event that completely changed your perspective on life?",
 "Do you like serious people? Or do you prefer to hang around light-hearted people?",
 "What’s a compliment that you regularly receive?",
 "What’s the one thing that drives you crazy about other people?",
 "What’s your greatest fear?",
 "How does your favorite music make you feel?",
 "What’s the most emotional scene you’ve ever seen in a movie?",
 "Do you prefer to be alone or around people?",
 "What’s something that just makes time seem to fly by ?",
 "Do you feel like you’re living life to the fullest? If not, why?",
 "What’s the type of person you enjoy being around the most?",
 "Do you think religion has been a good thing or a bad thing for the world?",
 "Are you a spiritual person?",
 "What does love mean to you?",
 "Have you ever had your heart broken?",
 "What’s the biggest thing you’ve done that you’ve been most proud of?",
 "When you hear the word “home”, what do you think of first?",
 "What’s the most consistent thing that you usually dream about?",
 "Do you think that there’s more to reality than what we see with our eyes?",
 "Do you think there is a purpose to life? Or is it all meaningless?",
 "Do you believe in marriage ?",
 "What do you think happens after death?",
 "If you could eradicate pain from your life, would you?",
 "Would you want to live forever? Why or why not?",
 "Would you rather love or be loved?",
 "What does true beauty mean to you?",
 "Do you like to have a routine every day?",
 "Where do you think happiness comes from?",
 "If you could ask me one question, and I had to answer truthfully, what would you ask me?",
 "What’s the best lesson about life you’ve ever learned?",
 "Are you priorities different now than they were in the past?",
 "What you rather be rich and single or poor and in love?",
 "What’s the hardest situation you’ve ever had to cope with in life?",
 "If you had to get a tattoo right now, what would you get?",
 "Do you think it’s important to be kind to everyone, or just to your friends?",
 "Are you an introvert or extrovert?",
 "Do you prefer to hang out with introverts or extroverts?",
 "What’s your best trait that you admire about yourself?",
 "What’s your worst trait that you wish you could change?",
 "What MUST you achieve before you die?",
 "When’s the last time you felt awe?",
 "What’s something you hate seeing other people do?",
 "What issue in society makes you most angry?",
 "What do you think about porn? Immoral or fine?",
 "What makes you most motivated in life?",
 "Who in your life do you wish you met sooner?",
 "What kinds of people do you simply not respect?",
 "Do you think its mind over matter? Or matter over mind?",
 "When do you feel you’re most confident?",
]

module.exports = questions